import type { Job, Profile, UserRole } from './types';

export const INITIAL_DEMO_JOBS: Job[] = [
  {
    id: '11111111-0000-0000-0000-000000000001',
    recruiter_id: 'recruiter-demo-id',
    title: 'Senior Frontend Engineer',
    company: 'Stripe',
    company_type: 'mnc',
    description:
      'Build delightful payment experiences used by millions. We use React, TypeScript, and a design system that sets the industry bar. You will own complex features end-to-end.',
    job_type: 'full_time',
    work_mode: 'remote',
    location: 'San Francisco, CA',
    salary_min: 180000,
    salary_max: 240000,
    currency: 'USD',
    experience_level: 'senior',
    skills_required: ['React', 'TypeScript', 'CSS', 'GraphQL', 'Node.js'],
    posted_at: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    is_active: true,
    created_at: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
  },
  {
    id: '11111111-0000-0000-0000-000000000002',
    recruiter_id: 'recruiter-demo-id',
    title: 'Product Designer',
    company: 'Figma',
    company_type: 'startup',
    description:
      'Shape the future of collaborative design tools. You will drive product design from research through high-fidelity prototypes, working closely with engineering.',
    job_type: 'full_time',
    work_mode: 'hybrid',
    location: 'San Francisco, CA',
    salary_min: 140000,
    salary_max: 190000,
    currency: 'USD',
    experience_level: 'mid',
    skills_required: ['Figma', 'Prototyping', 'Design Systems', 'User Research', 'CSS'],
    posted_at: new Date(Date.now() - 5 * 3600 * 1000).toISOString(),
    is_active: true,
    created_at: new Date(Date.now() - 5 * 3600 * 1000).toISOString(),
  },
  {
    id: '11111111-0000-0000-0000-000000000003',
    recruiter_id: 'recruiter-demo-id',
    title: 'Full Stack Engineer',
    company: 'Linear',
    company_type: 'startup',
    description:
      'Join a small, senior team building the issue tracking tool that developers love. React, Node.js, Postgres, and a relentless focus on speed.',
    job_type: 'full_time',
    work_mode: 'remote',
    location: 'Remote',
    salary_min: 150000,
    salary_max: 210000,
    currency: 'USD',
    experience_level: 'mid',
    skills_required: ['React', 'TypeScript', 'Node.js', 'PostgreSQL', 'GraphQL'],
    posted_at: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
    is_active: true,
    created_at: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
  },
  {
    id: '11111111-0000-0000-0000-000000000004',
    recruiter_id: 'recruiter-demo-id',
    title: 'Machine Learning Engineer',
    company: 'OpenAI',
    company_type: 'mnc',
    description:
      'Train and deploy large language models at scale. Strong background in PyTorch, distributed systems, and ML infrastructure required.',
    job_type: 'full_time',
    work_mode: 'hybrid',
    location: 'San Francisco, CA',
    salary_min: 250000,
    salary_max: 350000,
    currency: 'USD',
    experience_level: 'senior',
    skills_required: ['Python', 'PyTorch', 'Distributed Systems', 'ML', 'Kubernetes'],
    posted_at: new Date(Date.now() - 3 * 3600 * 1000).toISOString(),
    is_active: true,
    created_at: new Date(Date.now() - 3 * 3600 * 1000).toISOString(),
  },
  {
    id: '11111111-0000-0000-0000-000000000005',
    recruiter_id: 'recruiter-demo-id',
    title: 'DevOps Engineer',
    company: 'Vercel',
    company_type: 'startup',
    description:
      'Build and maintain the infrastructure powering millions of deployments. Experience with AWS, Kubernetes, Terraform, and CI/CD pipelines.',
    job_type: 'full_time',
    work_mode: 'remote',
    location: 'Remote',
    salary_min: 160000,
    salary_max: 220000,
    currency: 'USD',
    experience_level: 'mid',
    skills_required: ['AWS', 'Kubernetes', 'Terraform', 'Docker', 'CI/CD'],
    posted_at: new Date(Date.now() - 6 * 3600 * 1000).toISOString(),
    is_active: true,
    created_at: new Date(Date.now() - 6 * 3600 * 1000).toISOString(),
  },
  {
    id: '11111111-0000-0000-0000-000000000006',
    recruiter_id: 'recruiter-demo-id',
    title: 'Software Engineering Intern',
    company: 'Notion',
    company_type: 'startup',
    description:
      'Spend your summer building features for one of the fastest-growing productivity tools. Great for students passionate about React and product thinking.',
    job_type: 'internship',
    work_mode: 'remote',
    location: 'Remote',
    salary_min: 8000,
    salary_max: 12000,
    currency: 'USD',
    experience_level: 'entry',
    skills_required: ['React', 'TypeScript', 'JavaScript', 'CSS'],
    posted_at: new Date(Date.now() - 8 * 3600 * 1000).toISOString(),
    is_active: true,
    created_at: new Date(Date.now() - 8 * 3600 * 1000).toISOString(),
  },
  {
    id: '11111111-0000-0000-0000-000000000007',
    recruiter_id: 'recruiter-demo-id',
    title: 'Backend Engineer',
    company: 'Supabase',
    company_type: 'new_startup',
    description:
      'Help us build the open source Firebase alternative. Go, Postgres, realtime APIs, and edge functions at scale.',
    job_type: 'full_time',
    work_mode: 'remote',
    location: 'Remote',
    salary_min: 130000,
    salary_max: 180000,
    currency: 'USD',
    experience_level: 'mid',
    skills_required: ['Go', 'PostgreSQL', 'Docker', 'Kubernetes', 'API Design'],
    posted_at: new Date(Date.now() - 12 * 3600 * 1000).toISOString(),
    is_active: true,
    created_at: new Date(Date.now() - 12 * 3600 * 1000).toISOString(),
  },
  {
    id: '11111111-0000-0000-0000-000000000008',
    recruiter_id: 'recruiter-demo-id',
    title: 'Mobile Engineer (React Native)',
    company: 'Discord',
    company_type: 'mnc',
    description:
      'Build the mobile experience for 150M+ users. React Native, native modules, and a passion for smooth 60fps interactions.',
    job_type: 'full_time',
    work_mode: 'hybrid',
    location: 'San Francisco, CA',
    salary_min: 170000,
    salary_max: 230000,
    currency: 'USD',
    experience_level: 'senior',
    skills_required: ['React Native', 'TypeScript', 'iOS', 'Android', 'GraphQL'],
    posted_at: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
    is_active: true,
    created_at: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
  },
  {
    id: '11111111-0000-0000-0000-000000000009',
    recruiter_id: 'recruiter-demo-id',
    title: 'Data Scientist',
    company: 'Airbnb',
    company_type: 'mnc',
    description:
      'Analyze travel trends and build models that power search ranking and pricing. Python, SQL, and a love for clean data.',
    job_type: 'full_time',
    work_mode: 'remote',
    location: 'Remote',
    salary_min: 160000,
    salary_max: 210000,
    currency: 'USD',
    experience_level: 'mid',
    skills_required: ['Python', 'SQL', 'Machine Learning', 'Statistics', 'Tableau'],
    posted_at: new Date(Date.now() - 48 * 3600 * 1000).toISOString(),
    is_active: true,
    created_at: new Date(Date.now() - 48 * 3600 * 1000).toISOString(),
  },
  {
    id: '11111111-0000-0000-0000-000000000010',
    recruiter_id: 'recruiter-demo-id',
    title: 'Engineering Manager',
    company: 'Plaid',
    company_type: 'startup',
    description:
      'Lead a team of 6-8 engineers building financial infrastructure. People leadership, technical vision, and a track record of shipping.',
    job_type: 'full_time',
    work_mode: 'hybrid',
    location: 'San Francisco, CA',
    salary_min: 220000,
    salary_max: 290000,
    currency: 'USD',
    experience_level: 'lead',
    skills_required: ['Leadership', 'Architecture', 'Python', 'Go', 'System Design'],
    posted_at: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
    is_active: true,
    created_at: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
  },
  {
    id: '11111111-0000-0000-0000-000000000011',
    recruiter_id: 'recruiter-demo-id',
    title: 'Junior Frontend Developer',
    company: 'Cal.com',
    company_type: 'new_startup',
    description:
      'Perfect first role for a bootcamp grad or self-taught dev. We value eagerness to learn over years of experience. React + TypeScript.',
    job_type: 'full_time',
    work_mode: 'remote',
    location: 'Remote',
    salary_min: 70000,
    salary_max: 95000,
    currency: 'USD',
    experience_level: 'entry',
    skills_required: ['React', 'TypeScript', 'JavaScript', 'HTML', 'CSS'],
    posted_at: new Date(Date.now() - 18 * 3600 * 1000).toISOString(),
    is_active: true,
    created_at: new Date(Date.now() - 18 * 3600 * 1000).toISOString(),
  },
  {
    id: '11111111-0000-0000-0000-000000000012',
    recruiter_id: 'recruiter-demo-id',
    title: 'Security Engineer',
    company: 'Cloudflare',
    company_type: 'mnc',
    description:
      'Protect the internet. Application security, threat modeling, and building tools that secure infrastructure at global scale.',
    job_type: 'full_time',
    work_mode: 'remote',
    location: 'Remote',
    salary_min: 180000,
    salary_max: 250000,
    currency: 'USD',
    experience_level: 'senior',
    skills_required: ['Security', 'Python', 'Go', 'Networking', 'Cryptography'],
    posted_at: new Date(Date.now() - 72 * 3600 * 1000).toISOString(),
    is_active: true,
    created_at: new Date(Date.now() - 72 * 3600 * 1000).toISOString(),
  },
];

export const DEMO_PROFILES: Profile[] = [
  {
    id: 'seeker-demo-id',
    role: 'seeker',
    full_name: 'Alex Johnson',
    avatar_url: '',
    skills: ['React', 'TypeScript', 'CSS', 'Node.js'],
    experience_years: 3,
    education: 'B.S. Computer Science',
    bio: 'Frontend developer passionate about building intuitive user experiences.',
    portfolio_links: ['https://github.com/demo-alex', 'https://alex-portfolio.dev'],
    location: 'San Francisco, CA',
    phone: '',
    created_at: new Date(Date.now() - 30 * 86400 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'recruiter-demo-id',
    role: 'recruiter',
    full_name: 'Sarah Chen',
    avatar_url: '',
    skills: ['Technical Recruiting', 'Talent Acquisition'],
    experience_years: 6,
    education: 'B.A. Communications',
    bio: 'Lead Talent Partner at Stripe. Hiring top software engineers and designers.',
    portfolio_links: ['https://linkedin.com'],
    location: 'New York, NY',
    phone: '',
    created_at: new Date(Date.now() - 60 * 86400 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'admin-demo-id',
    role: 'admin',
    full_name: 'Marcus Vance',
    avatar_url: '',
    skills: ['Platform Management', 'Operations'],
    experience_years: 8,
    education: 'M.S. Information Systems',
    bio: 'Platform Administrator for SwipeX.',
    portfolio_links: [],
    location: 'Austin, TX',
    phone: '',
    created_at: new Date(Date.now() - 90 * 86400 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const DEMO_USERS = [
  {
    id: 'seeker-demo-id',
    email: 'seeker@demo.com',
    password: 'password123',
    full_name: 'Alex Johnson',
    role: 'seeker' as UserRole,
  },
  {
    id: 'recruiter-demo-id',
    email: 'recruiter@demo.com',
    password: 'password123',
    full_name: 'Sarah Chen',
    role: 'recruiter' as UserRole,
  },
  {
    id: 'admin-demo-id',
    email: 'admin@demo.com',
    password: 'password123',
    full_name: 'Marcus Vance',
    role: 'admin' as UserRole,
  },
];

export function analyzeResumeLocally(text: string) {
  const knownSkills = [
    'JavaScript', 'TypeScript', 'React', 'Vue', 'Angular', 'Node.js', 'Express',
    'Next.js', 'Nuxt.js', 'Python', 'Django', 'Flask', 'FastAPI', 'Java', 'Spring',
    'Kotlin', 'Swift', 'Go', 'Rust', 'C++', 'C#', '.NET', 'Ruby', 'Rails',
    'PHP', 'Laravel', 'SQL', 'PostgreSQL', 'MySQL', 'MongoDB', 'Redis',
    'GraphQL', 'REST', 'Docker', 'Kubernetes', 'AWS', 'GCP', 'Azure',
    'Terraform', 'CI/CD', 'Git', 'HTML', 'CSS', 'Tailwind', 'Figma',
    'Machine Learning', 'PyTorch', 'TensorFlow', 'Data Science', 'Statistics',
    'React Native', 'iOS', 'Android', 'Leadership', 'Architecture', 'System Design',
    'Security', 'DevOps', 'Agile', 'Scrum', 'Testing', 'Jest', 'Webpack', 'Vite',
  ];

  const lower = text.toLowerCase();
  const matched = knownSkills.filter((s) => lower.includes(s.toLowerCase()));

  // Score based on skills found
  const baseScore = Math.min(95, Math.max(55, 50 + matched.length * 5));

  const suggestions: string[] = [];
  if (!matched.some((s) => ['Git', 'CI/CD', 'Docker'].includes(s))) {
    suggestions.push('Add DevOps & collaboration keywords (Git, CI/CD, Docker) to improve technical score.');
  }
  if (!matched.some((s) => ['TypeScript', 'Testing', 'Jest'].includes(s))) {
    suggestions.push('Highlight TypeScript or testing frameworks (Jest, Cypress) for higher engineering match.');
  }
  if (matched.length < 5) {
    suggestions.push('Include more specific technology keywords relevant to your target roles.');
  }
  suggestions.push('Use quantifiable metrics and business impact in your work experience bullet points.');

  return {
    ats_score: baseScore,
    parsed_skills: matched.length > 0 ? matched : ['React', 'JavaScript', 'CSS', 'Git'],
    suggestions,
  };
}
